# build stage
FROM node:20-alpine as build

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .

# Accept build arguments
ARG VITE_USER_SERVICE_URL
ARG VITE_API_VERSION

# Make them available to Vite during build
ENV VITE_USER_SERVICE_URL=$VITE_USER_SERVICE_URL
ENV VITE_API_VERSION=$VITE_API_VERSION

RUN npm run build

# production stage
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

# EXPOSE 5173
EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]

# FROM node:20-alpine

# WORKDIR /app

# COPY package*.json ./
# RUN npm install

# COPY . .

# EXPOSE 5173

# CMD ["npm", "run", "dev", "--", "--host"]