version: "3.8"

services:
  api_gateway:
    build: ./Api_Gateway
    ports:
      - "5000:5000"
    volumes:
      - ./Api_Gateway:/app
      - /app/node_modules
    depends_on:
      - user_service
      - room_inventory_service
      - guest_service
      - payment_service
      - reservation_service
    env_file:
      - ./Api_Gateway/.env

  user_service:
    build: ./User_Service
    ports:
      - "8000:8000"
    volumes:
      - ./User_Service:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  room_inventory_service:
    build: ./room_inventory_service
    ports:
      - "8090:8090"
    depends_on:
      - user_service

  guest_service:
    build: ./Guest_Engagement_Service
    ports:
      - "8070:8070"
    volumes:
      - ./Guest_Engagement_Service:/app
      - /app/node_modules
    depends_on:
      - user_service
      - reservation_service
      - room_inventory_service
      - payment_service
    env_file:
      - ./Guest_Engagement_Service/.env

  payment_service:
    build: ./Payment_Service
    ports:
      - "8050:8050"
    volumes:
      - ./Payment_Service:/app
      - /app/node_modules
    depends_on:
      - user_service

  reservation_service:
    build: ./Reservation_Service
    ports:
      - "8060:8060"
    env_file:
    - ./Reservation_Service/.env
    depends_on:
      - user_service
      - room_inventory_service

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host
    depends_on:
      - api_gateway
      - user_service
      - payment_service
      - room_inventory_service
      - reservation_service
